### ISSUE TITLE
Docker is not running error

### ISSUE THREAD

**Issue by joshstobbs** [V13Axel/neotest-pest#1]
Apologies for the somewhat light bug report, I've just setup this fork after finding in the other `neotest-pest` repo - the setup went quite smoothly though when looking to run tests I'm getting a `Docker is not running.` error.  I'm a bit new to testing in Neovim so maybe this is outside the bounds of this plugin but any help would be appreciated!

Running tests through the artisan cli seems to work just fine.  Also I see you've added support for Sail, in this particular instance I am running Herd as opposed to Sail for my dev environment.

Anyway, thanks much for taking on the maintenance burden of this plugin!

![CleanShot 2024-02-13 at 13 38 55](https://github.com/V13Axel/neotest-pest/assets/57326077/8f843899-3637-4b08-9bd5-6bbd10046a8f)

**Comment by V13Axel** [comment]
Ohh, interesting! I do all of my development on Linux and as such have no experience with Herd, though I am aware of it through colleagues.

I'd say it's definitely within the bounds of what I'm trying to achieve with this adapter, so no worries there!

Few questions:
1. When you run your tests, what command(s) do you run to make that happen?
2. Does Herd create any special binaries or configuration within the project? `sail` creates `vendor/bin/sail`, which makes it pretty easy to detect. Just trying to think about how to detect a Herd project.
3. If not 2, any other ideas for detecting a project running with Herd?

**Comment by V13Axel** [comment]
Oh, I see! To me that sounds like it might be wrongly thinking `sail` exists - Curious to hear, are you able to run `vendor/bin/pest` directly?

**Comment by joshstobbs** [comment]
Hey!  Yep, I can run the pest binary directly.

**Comment by V13Axel** [comment]
Hmm, that sounds super strange - though I did just make a bunch of changes yesterday (with a bunch of configurability!) that may have fixed it. Can you try with the latest version of the adapter?

**Comment by joshstobbs** [comment]
Okay!  We're getting _somewhere_, aha!

The Docker error is no longer showing up but I'm getting this when I try to run a test function/file.  Any thoughts?

Also thank you for all the help so far, it's very appreciated!

![CleanShot 2024-02-21 at 08 20 10](https://github.com/V13Axel/neotest-pest/assets/57326077/2b5ba0ab-9792-4747-8bb5-131a94584b6b)

**Comment by V13Axel** [comment]
Hmm, "No test output file found!" typically means the test process crashed midway and wasn't able to create the XML output file that the adapter parses to determine test results. The `junit` bit is expected[^1]

That said, the relative path you have there (`storage/app/...`) gets set when the adapter detects the _presence_ of `sail`. I'm tinkering with detecting whether `sail` is actually _running_, but for now it's just enabled by default if the file `vendor/bin/sail` is present. It sounds to me like your project has sail _installed_, but you don't use it? If that's the case, you'll just need to override `sail_enabled` to false in your config:

```lua
require('neotest').setup({
    adapters = {
        require('neotest-pest')({
            sail_enabled = false
        }),
    }
})
```

If it's still crashing after that, here's how you can nail that down:
1. Add `log_level = vim.log.levels.DEBUG` to your `require('neotest').setup({})` 
2. Try running your test(s) again
3. Check the neotest log (I don't know where that will be on mac, but mine is at `~/.local/state/nvim/neotest.log`), looking for a debug log entry of `Command:` and it should show you the exact command being run. Here's an example of mine when running with `sail`:

```lua
{ "vendor/bin/sail", "bin", "pest", "/var/www/html/tests/Feature/LocationAgnosticJobListTest.php", "--log-junit=storage/app/junit-20240222-091915", "--filter", "can change departments quickly" }
```

versus without:

```lua
{ "vendor/bin/pest", "/home/axel/Git/neotest-pest/tests/Feature/UserTest.php", "--log-junit=/tmp/nvim.axel/isXpIm/3", "--filter", "class constructor" }
```

4. If it's not `sail`, try running that command directly, see what happens? ... if it _is_ still sail with `sail_enabled = false`, let me know! Would be a weird edge case I think.

---
[^1]: Pest uses PHPUnit under the hood, which involves junit somewhere along the line. The flag for setting that filename is `--log-junit`, which is why it's named that, but honestly I should probably change the default filename format to `pest-[date]` instead.

**Comment by joshstobbs** [comment]
Wow!  Thanks for the detailed response - so after doing some testing here's what I've come to:

1. You were right `sail` was installed in the repo, in fact it seems like `sail` is automatically installed when using the Laravel installer.
2. I set `sail_enabled` to `false` and the plugin still seemed to look for the `sail` binary:
    a. my command output: `{ "vendor/bin/sail", "bin", "pest", "/var/www/html/tests/Unit/UserTest.php", "--log-junit=storage/app/junit-20240222-115735", "--filter", "a designer sees their projects" }`
3. Removing `sail` from my project and unsetting `sail_enabled = false` in my config seems to have done the trick and now I am able to run tests.

Maybe this is just a comedy of errors on my part...or like you say, perhaps a weird edge case.  Regardless things _are_ working on my end, and quite well, thank you!  I'm happy to do anymore debugging if you need it!

**Comment by lizhineng** [comment]
I have encountered similar issues when testing a Laravel project since Sail is automatically installed with a new installation. Setting the `sail_enabled` config to `false` does not turn the feature off. Instead, configuring it with a function resolves the issue. As a newcomer to Lua, I am not familiar with the problem. Perhaps the issue relates to type conversion since one is a function and the other is a boolean value?

```lua
require('neotest-pest')({
  sail_enabled = function ()
    return False
  end
})
```

**Comment by V13Axel** [comment]
Well, the way I've written the config _should_ support either callable or non-callable values. I'll tinker with that, but glad to hear setting it to a function solved it for you =]
