### ISSUE TITLE
No test output file found

### ISSUE THREAD

**Issue by Mourishitz** [V13Axel/neotest-pest#8]
Hey, I just installed the latest version of [AstroNvim](https://astronvim.com/) (which does support neotest on its community packages using Lazy).

I just overwrote the plugin like this:
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/4dd27300-7a70-4a39-8035-ea58ed600bd9)

[Check the full file here](https://gist.github.com/Mourishitz/1412fbafc3734e4d94a80004998ce31a)
 
All of a sudden, it does not work properly and gives this output:

![image](https://github.com/V13Axel/neotest-pest/assets/97261428/920cdd47-36c1-44e0-b34e-946c6425a65c)

I've saw the issue #5 with similar problems, but those did not work for me.

can I at least get a hint of what could be causing that to pop up?

**Comment by noreason** [comment]
In my experience, this is usually caused by the command you specified not actually running, or crashing.

In your config, you set the command as `vendor/bin/pest` (which is the default by the way so you don't have to set it) and explicitly set sail to disabled. So really nothing is wrong here that I can tell.

My guess, and sorry but I have to ask even if it sounds trivial, do you actually have pest installed in the project? Meaning, can you successfully run `vendor/bin/pest` from the root directory and see the tests run? Does it run to completion?

Let me know if the command runs fine or if it fails, then I can try to help you out a bit more.

**Comment by Mourishitz** [comment]
Sure! It is not trivial at all, could really be an issue if Pest was not configured properly..

Turns out it is a valid command
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/65c54dee-fe57-4b21-9ef2-8f1958562511)

**Comment by Mourishitz** [comment]
Also, I forgot to mention but I already tried variants of this command such as `./vendor/bin/pest`

**Comment by noreason** [comment]
Ok thanks, my next guess is that there is an issue determining the project root maybe? I'm not familiar with AstroVims plugins, but maybe it has a projects style plugin or another plugin that is adjusting the working directory.

Check and see that your current working directory is the same as where you just ran that `vendor/bin/pest --version` command. You can check this by typing `:pwd` inside neovim with your test file open. It should output a path that should match the _exact_ path that you are able to run `vendor/bin/pest` from.

**Comment by V13Axel** [comment]
Also hate to ask what seems like a silly question: When you run just `vendor/bin/pest` via your shell to try and run your tests, does that work?

**Comment by Mourishitz** [comment]
Sure it does! Here is an example of it running
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/ed51cb50-3923-4296-8577-f1a5ffb78ad8)

**Comment by V13Axel** [comment]
Hmm. My next thought is to add `  log_level = vim.log.levels.WARN,` to your neotest config, and then tail the contents of `~/.local/state/nvim/neotest.log` to see what it says

**Comment by noreason** [comment]
I just reproduced this on my end.

You mentioned in the beginning 

> I've saw the issue https://github.com/V13Axel/neotest-pest/issues/5 with similar problems, but those did not work for me.

So i just assumed that this was a different issue.

You'll need to pull the most recent version of this plugin which has the PR i submitted that closed out #5...

That should™ solve your problem.

**Comment by V13Axel** [comment]
Ah, this makes it clear to me:

```
invalid node type at position 196 for language php
```

That's happening because you're using the latest tree-sitter and _not_ the latest (as of a couple hours ago) version of this repo. Update to the latest and you _ought to I think maybe_ be good to go.

However, if you're using any heredocs with language injections, you'll instead want to pin tree-sitter to the older commit (as described by another user in #7) and then pin _this_ plugin to the commit just before latest.

To be clear, that's stuff like

```php

$someValue = <<<JSON
    { 'some': 'json here' }
JSON;
```

^ There's a tree-sitter bug right now that will cause neovim to segfault if you do that. =]

**Comment by V13Axel** [comment]
Heh, just realized @noreason beat me to responding - Thank you sir. :slightly_smiling_face:

**Comment by Mourishitz** [comment]
Yeah, it kind of worked.. When I run it under cursor or file it goes perfect!
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/019be3f2-a170-4108-9ce4-c4e84c2507c0)
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/223e0b3e-6b39-46be-9335-169b3fa4f79d)
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/70fc328f-e6f4-4f03-8d7a-35fb4555fda5)

Now, for some reason it still logs out errors when trying to run tests for the project..
What I mean by "run tests for the project" is running on this command:
![image](https://github.com/V13Axel/neotest-pest/assets/97261428/e36d23c8-d8c1-459e-89e1-2ea9365b7b76)

**Comment by Mourishitz** [comment]
This might be some problem with my vim config.. I can close the issue for now (if it is ok to you guys)

I would like to really thank you for helping me out! It is working great

**Comment by V13Axel** [comment]
I keep my tests under `{projectroot}/tests`, so I just have my "run project" keybind setup like this:

```lua
vim.keymap.set('n', '<leader>tr', function() require('neotest').run.run("tests") end)
```

Maybe using a relative path would work for you too? Either way, definitely seems outside of the scope of this issue, so I'm gonna call it closed.
